apiVersion: v1
kind: Pod
metadata:
  name: "podman"
  namespace: devops
  labels:
    app: "podman"
spec:
  containers:
    - name: podman
      image: "quay.io/podman/stable:latest"
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 200Mi
      args:
        - "sleep"
        - "infinity"
  restartPolicy: Never
